### ISSUE TITLE
On Admin portal npm start, UI crashes

### ISSUE THREAD

**Issue by Kalyan001** [navinesh/leave-management-system#16]
TypeError: Cannot read property 'findLeaveRecord' of undefined
PendingLeave
D:/DIR/LMS/admin/src/containers/PendingLeave.tsx:65
  62 |   }
  63 | `;
  64 | 
> 65 | export default function PendingLeave(): JSX.Element {
  66 |   const client = useApolloClient();
  67 | 
  68 |   const { data } = useQuery(IS_AUTHENTICATED);
View compiled
▶ 16 stack frames were collapsed.
Module../src/index.tsx
D:/DIR/LMS/admin/src/index.tsx:142
  139 |   );
  140 | }
  141 | 
> 142 | ReactDOM.render(<App />, document.getElementById('root'));
  143 | 
  144 | serviceWorker.register();
  145 | 
View compiled
__webpack_require__
D:/DIR/LMS/admin/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
D:/DIR/LMS/admin/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/static/js/main.chunk.js:4095:18
__webpack_require__
D:/DIR/LMS/admin/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
checkDeferredModules
D:/DIR/LMS/admin/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
D:/DIR/LMS/admin/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:63
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by navinesh** [comment]
This issue has been fixed.
